name: flutter_pagination
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+3
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
flutter:
  uses-material-design: true
