name: flutter_pagination
description: A new Flutter application.
version: 1.1.0+2
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
flutter:
  uses-material-design: true
